### ISSUE TITLE
'authProvider' is required for createUser mutation

### ISSUE THREAD

**Issue by mkozhukharenko** [graphcool-examples/functions#68] opened 2017-08-18 16:21 UTC
```
mutation {
        createUser(
          accountKitUserId:"${accountKitUser.id}"
        ){
          id
        }
      }
```

this mutation is not valid in case if ‘Email-password auth’ integration is enabled - the ‘authProvider’ field is required.

**Comment by marktani** [comment] 2017-08-18 16:51
That's correct - all custom authentication examples in this repository assume that no authentication provider is enabled in your project. You should be able to migrate the current email-password auth to something similar to [this example](https://github.com/graphcool-examples/functions/tree/master/authentication/email-user-management).

**Comment by mkozhukharenko** [comment] 2017-08-20 11:02
consider next scenario:
1) the email-pass auth provide is enabled
2) accoukKit phone auth is set up
3) user don't have an account (neight email-pass, nor accountKit using phone)
4) user trying to login using accountKit phone auth

but we can't sign him up since using only his phone since his email is required!

**Comment by marktani** [comment] 2017-08-20 20:59
> the email-pass auth provide is enabled

you can replace and even cover more advanced scenarios with something similar to [this](https://github.com/graphcool-examples/functions/tree/master/authentication/email-user-management) using Schema Extensions. Then you can include the logic that handles the sync between account kit and email sign ups in your functions, too. :slightly_smiling_face:

**Comment by mkozhukharenko** [comment] 2017-08-20 21:51
If user NEVER signed to my app before and is trying to sign using his phone number only -> I can't sign him in since EMAIL is REQUIRED by backend.

please, try to understand the situation. It's a problem.

**Comment by marktani** [comment] 2017-08-21 10:02
Hey @mkozhukharenko I understand the situation, and it's caused by the limited possibilities of the email-pass provider. The reason the `email` field is required, is because the email-pass provider is enabled. That's why I wrote

> all custom authentication examples in this repository assume that no authentication provider is enabled in your project.

Now, if you disable the email-pass provider, and replace it with your own implementation, the `email` field doesn't have to be required anymore, because that's all in your control now.

Of course, if you actually WANT the email field to be required, you'd need to adjust the sign up flow using account kit to also include an email address.

I agree that this is a problem, and I am trying to show you potential approaches to tackle it 🙂 Do you understand my suggestion now? I wasn't as clear before, sorry!

**Comment by mkozhukharenko** [comment] 2017-08-21 10:08
>  and replace it with your own implementation

sorry, I didn't understand that you are talking about replacing email-auth with own implementation. I thought you meant extending it. 

now everything is clear.

**Comment by marktani** [comment] 2017-08-21 10:15
Great, thanks again for bringing up this confusion! I'll close this issue 🙂

**Closed by marktani** 2017-08-21 10:15 UTC
